### ISSUE TITLE
Removed names from license file

### ISSUE THREAD

**Issue by tfheen** [BlitzKraft/wee-discord#1]
It looks like this is pretty much based on Ryan's and my work on wee-slack (and you write that in the README too).  However, it looks like you've removed our copyrights from the license file.  This is not ok as long as there are copyrighted pieces from us in wee-discord, so could you please put them back?

(I'm not asking you to stop on wee-discord or anything, good luck on the project, I'm just asking to be credited.)

**Comment by BlitzKraft** [comment]
Yes, I will add that. 

Honestly, I haven't started working on it yet. I forked it a while ago and it is in stasis ever since.

**Comment by BlitzKraft** [comment]
My bad, I didn't understand the license well. Fixed.

**Comment by tfheen** [comment]
]] BK 

> My bad, I didn't understand the license well. Fixed. 

Thanks! :-)

## 

Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are
